apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-master-pv
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /mnt/data/mysql-master

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-master-pvc
spec:
    resources:
        requests:
            storage: 1Gi
    accessModes:
        - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-slave-pv
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /mnt/data/mysql-slave

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-slave-pvc
spec:
    resources:
        requests:
            storage: 1Gi
    accessModes:
        - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-master
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
            role: master
    template:
        metadata:
            labels:
                app: mysql
                role: master
        spec:
            containers:
                - name: mysql-master
                  image: mysql:8.0
                  args:
                      - --server-id=1
                      - --log-bin=mysql-bin
                      - --binlog-format=row
                      - --port=3309
                      - --default_authentication_plugin=mysql_native_password
                  ports:
                      - containerPort: 3309
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        value: "H@punCel9"
                      - name: MYSQL_DATABASE
                        value: "heardittracks"
                  volumeMounts:
                      - name: mysql-master-storage
                        mountPath: /var/lib/mysql
                      - name: mysql-initdb
                        mountPath: /docker-entrypoint-initdb.d
            volumes:
                - name: mysql-master-storage
                  persistentVolumeClaim:
                      claimName: mysql-master-pvc
                - name: mysql-initdb
                  configMap:
                      name: mysql-initdb
                      items:
                          - key: heardittracks20240612.sql
                            path: heardittracks20240612.sql

---
apiVersion: v1
kind: Service
metadata:
    name: mysql-master
spec:
    ports:
        - port: 3309
    selector:
        app: mysql
        role: master

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-slave
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
            role: slave
    template:
        metadata:
            labels:
                app: mysql
                role: slave
        spec:
            containers:
                - name: mysql-slave
                  image: mysql:8.0
                  args:
                      - --server-id=2
                      - --log-bin=mysql-bin
                      - --binlog-format=row
                  ports:
                      - containerPort: 3308
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        value: "H@punCel9"
                      - name: MYSQL_DATABASE
                        value: "heardittracks"
                      - name: MYSQL_REPLICATION_USER
                        value: "repluser"
                      - name: MYSQL_REPLICATION_PASSWORD
                        value: "H@punCel9"
                  volumeMounts:
                      - name: mysql-slave-storage
                        mountPath: /var/lib/mysql
                      - name: mysql-initdb
                        mountPath: /docker-entrypoint-initdb.d
            volumes:
                - name: mysql-slave-storage
                  persistentVolumeClaim:
                      claimName: mysql-slave-pvc
                - name: mysql-initdb
                  configMap:
                      name: mysql-initdb
                      items:
                          - key: heardittracks20240612.sql
                            path: heardittracks20240612.sql

---
apiVersion: v1
kind: Service
metadata:
    name: mysql-slave
spec:
    ports:
        - port: 3308
    selector:
        app: mysql
        role: slave
