apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: jumorto/mysql-heardittracks:latest
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        value: "H@punCel9"
                      - name: MYSQL_DATABASE
                        value: "heardittracks"
                  ports:
                      - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-1
spec:
    selector:
        app: mysql
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
    type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: search-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: search-service
    template:
        metadata:
            labels:
                app: search-service
        spec:
            containers:
                - name: search-service
                  image: jumorto/heardit-search-service:latest
                  ports:
                      - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
    name: search-service
spec:
    selector:
        app: search-service
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 8081
    type: LoadBalancer
