apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: jumorto/mysql-heardittracks:latest
                  imagePullPolicy: Always
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        value: "H@punCel9"
                      - name: MYSQL_DATABASE
                        value: "heardittracks"
                  ports:
                      - containerPort: 3306
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-1
spec:
    selector:
        app: mysql
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
    type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: search-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: search-service
    template:
        metadata:
            labels:
                app: search-service
        spec:
            containers:
                - name: search-service
                  image: jumorto/heardit-search-service:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8081
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "250m"
                      limits:
                          memory: "256Mi"
                          cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
    name: search-service
spec:
    selector:
        app: search-service
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 8081
    type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: songmanager-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: songmanager-service
    template:
        metadata:
            labels:
                app: songmanager-service
        spec:
            containers:
                - name: songmanager-service
                  image: jumorto/heardit-songmanager-service:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8082
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "250m"
                      limits:
                          memory: "256Mi"
                          cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
    name: songmanager-service
spec:
    selector:
        app: songmanager-service
    ports:
        - protocol: TCP
          port: 8082
          targetPort: 8082
    type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: rabbitmq-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: rabbitmq-service
    template:
        metadata:
            labels:
                app: rabbitmq-service
        spec:
            containers:
                - name: rabbitmq-service
                  image: jumorto/heardit-rabbitmq-service:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8083
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "250m"
                      limits:
                          memory: "256Mi"
                          cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
    name: rabbitmq-service
spec:
    selector:
        app: rabbitmq-service
    ports:
        - protocol: TCP
          port: 8083
          targetPort: 8083
    type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: rabbitmq-server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: rabbitmq-server
    template:
        metadata:
            labels:
                app: rabbitmq-server
        spec:
            containers:
                - name: rabbitmq-server
                  image: rabbitmq:3-management
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 5672
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "250m"
                      limits:
                          memory: "256Mi"
                          cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
    name: rabbitmq-server
spec:
    selector:
        app: rabbitmq-server
    ports:
        - protocol: TCP
          port: 5672
          targetPort: 5672
    type: ClusterIP

---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
    name: eg
spec:
    controllerName: gateway.envoyproxy.io/gatewayclass-controller

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
    name: eg
spec:
    gatewayClassName: eg
    listeners:
        - name: http
          protocol: HTTP
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: search-service
spec:
    parentRefs:
        - name: eg
    rules:
        - backendRefs:
              - group: ""
                kind: Service
                name: search-service
                port: 8081
                weight: 1
          matches:
              - path:
                    type: PathPrefix
                    value: /api/search
        - backendRefs:
              - group: ""
                kind: Service
                name: songmanager-service
                port: 8082
                weight: 1
          matches:
              - path:
                    type: PathPrefix
                    value: /api/manage
        - backendRefs:
              - group: ""
                kind: Service
                name: rabbitmq-service
                port: 8083
                weight: 1
          matches:
              - path:
                    type: PathPrefix
                    value: /api/rabbitmq
