# Automatically build and test HeardIT back-end on push and pull-request
# using GitHub Actions.

name: HeardIT pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker build -t jumorto/heardit-backend .
          docker login -u jumorto -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push jumorto/heardit-backend

#      - name: Run Docker container
#        run: docker run -p 8080:8080 heardit-backend