# Automatically build and test HeardIT back-end on push and pull-request
# using GitHub Actions.

name: HeardIT build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

  code_quality_and_security:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download and cache SonarCloud CLI
        uses: actions/cache@v2
        with:
          path: |
            ~/.sonar/cache
          key: sonarcache
          restore-keys: |
            sonarcache

      - name: Analyze code with SonarCloud
        run: |
          ./gradlew sonarqube -Dsonar.organization=jumoorg -Dsonar.projectKey=Jumorto_HeardIT -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
#      - name: Run OWASP Dependency-Check
#        run: |
#          ./gradlew dependencyCheckAnalyze -Djarsigner.skip=true
#
#      - name: Upload OWASP Dependency-Check report
#        uses: actions/upload-artifact@v2
#        with:
#          name: dependency-check-report
#          path: build/reports/dependency-check-report.html
